# brian's standard Travis CI config for Perl 5 modules
# https://github.com/briandfoy/brians_perl_modules_travis_config
# This file is licensed under the Artistic License 2.0

sudo: false

language: perl
perl:
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"
    - "5.28"
    - "5.30"

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init --auto

install:
    - cpanm --quiet --installdeps --notest .
    - cpanm --quiet --notest Devel::Cover
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    - cover -delete && cover -test

after_success:
    - cover -report coveralls
