name: libarchive

on:
    push:
        branches:
            - 'libarchive'

jobs:
    perl:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os:
                - macos-latest
            perl-version:
                - 'latest'
        steps:
            - uses: actions/checkout@v2
            - name: Platform check
              run: uname -a
            - name: Perl version check
              run: perl -V
            - name: Install cpanm and multiple modules
              run: |
                curl -L https://cpanmin.us | perl - App::cpanminus
            - name: Install libarchive
              env:
                ALIEN_LIBARCHIVE: 'share'
              run: |
                cpan -M https://www.cpan.org/ Alien::Libarchive
                cpan -M https://www.cpan.org/ Archive::Extract::Libarchive
